### ISSUE TITLE
context.merge should be a hook

### ISSUE THREAD

**Issue by ghost** [ues-io/uesio#2297]
The metric component uses merge syntax to get it's value:

```
                - uesio/io.metric:
                    title: Time Worked
                    unit: Hours
                    value: $Sum{entries:tcm/timetracker.hours}
```

that value is based on a wire called **entries**.
Before the styling change, this component was re-rendering, but currently, this is not the case.

inside the metric component we use:

```
const value = context.merge(definition.value)
```

if this was a hook context.UseMerge() the component will re-render.

┆Issue is synchronized with this [Clickup ](https://app.clickup.com/t/860qmq3mj) by [Unito](https://www.unito.io)
