### ISSUE TITLE
Picking a Date in the View builder Bombs the page after save it

### ISSUE THREAD

**Issue by ghost** [ues-io/uesio#2611]
![image](https://github.com/TheCloudMasters/uesio/assets/65349612/2f810d61-b4a6-49cb-94f1-c8c2e1f2e01a)

Quick question maybe you might know how to approach this.
It took me a while to find out but I will try to explain as better as I can;
This works (notice double quotes on the value)-->

```
conditions:
      - field: uesio/tests.date
        operator: EQ
        valueSource: VALUE
        value: "2023-06-19"
```

This not -->

```
conditions:
      - field: uesio/tests.date
        operator: EQ
        valueSource: VALUE
        value: 2023-06-19
```

both are string in Redux, and being send to the wire load as strings;
But if you add the second type the page explodes, showing the message you see in the image.
when we try to preload the wires on a view and try to unmarshalConditions the yaml v3 decorder do the smart thing of getting the string and changing it to TIME, and then the pgx don’t know what to do with time.
In the past me & Ben tried to avoid changing the unmarshalConditions and write a field by field decoder, but I think this might be our only solution.
Happy to show you on a call if you need more details.

┆Issue is synchronized with this [Clickup ](https://app.clickup.com/t/85ztck0x7) by [Unito](https://www.unito.io)
