### ISSUE TITLE
bug: `defaultVariant` property in component yaml not respected in builder runtime

### ISSUE THREAD

**Issue by techfg** [ues-io/uesio#4434]
When a component has defined a `defaultVariant` property, the value assigned is not respected in "Builder" mode.

For example, if the yaml for [text component[(https://github.com/ues-io/uesio/blob/master/libs/apps/uesio/io/bundle/components/text.yaml) was modified to be:

```yaml
name: text
title: Text
defaultVariant: uesio/io.iconoutline
....
```

The `iconoutline` would not be applied when viewing in Builder canvas.

When "previewing" the view, the `defaultVariant` is applied - it's only in the builder that this problem surfaces.
