### ISSUE TITLE
feat: SEO improvements

### ISSUE THREAD

**Issue by techfg** [ues-io/uesio#4572]
Would like to see the following added to the platform:

1. Ability to define redirects for both HTTP 301 & 302.  For example, let's say routes changed from /blog/* to /news/*, while the site works at the new url, any previous links to blog will no longer work OOB.  This not only affects someone with a link (or a site that contains a link to the old urls) but also SEO impacts for google/bing/etc.
2. Add a "canonical" tag to HTML head element for the current page url
3. Bonus Item - Auto generate a site map and make available

**Comment by zachelrath** [comment]
@techfg There are a number of SEO features currently supported.

1. Redirects are already supported you can define a Route with `type: redirect` and `redirect: /some/other/url`, and that will cause a 302 Redirect to be performed when someone accesses that route.
2. Canonical link tags can already be added to any Route via Route Tags ( `tags` property). For example, this is the Route definition for the Uesio documentation home route:

```
name: home
public: true
path: home
view: home
params:
  slug: home
theme: default
title: $Site{title} - Documentation
tags:
  - type: meta
    location: head
    name: description
    content: Home page for ues.io documentation
  - type: link
    location: head
    name: canonical
    content: $Site{url}
```
3. Agreed about the need for custom Site Maps - a couple years ago we were discussing allowing you to define a Bot that generates a Site Map, similar to what Next.js supports . 

However, we decided then to keep things simple for the time, and just implement a default robots.txt route, which gets you pretty far with SEO without having to define a full site map. What we implemented was this --- by default all Routes are blocked from crawlers, but any publicly-accessible Routes (Routes which your app's Public Profile can access) are marked as allowed, so that crawlers can index them. However, this is enabled on a per-Site basis, since, for example, you wouldn't want your QA/UAT site to be indexed by crawlers, generally you only want your Production site to be crawled. Thus, there is an "Enable SEO" checkbox on Sites, which turns on this behavior.
